Fixes mdoc/mdl section
openid/OpenID4VP pull request #128
Opened 2024-03-06 16:20 UTC by awoie

This PR fixes the mso_mdoc sections by referencing to the relevant documents that define the profile.

Fixes #62

2024-03-06 21:06 UTC, Sakurann requested changes
I don't think there was an agreement in issue #62 to remove examples and only point to ISO specs.

also if you want to mention both 18013 and 23220, much more explanation is needed about the relationship between them. I am afraid the current text would confuse those not familiar.

2024-03-06 21:53 UTC, awoie commented
> I don't think there was an agreement in issue #62 to remove examples and only point to ISO specs.
> 
> also if you want to mention both 18013 and 23220, much more explanation is needed about the relationship between them. I am afraid the current text would confuse those not familiar.



> I don't think there was an agreement in issue #62 to remove examples and only point to ISO specs.
> 
> also if you want to mention both 18013 and 23220, much more explanation is needed about the relationship between them. I am afraid the current text would confuse those not familiar.

Ok, let's discuss in the issue first.

On the PR, I can give an intro sentence on what mdocs are similar to what we did for anoncreds. No need to mention more. For that reason the references for interested readers.

2024-03-25 12:59 UTC, awoie commented
@Sakurann I tried to incorporate your feedback in the PR. Could you please review again.

2024-03-28 04:29 UTC, Sakurann commented on openid-4-verifiable-presentations-1_0.md
> +   -21
```suggestion

   -21
```

2024-03-28 04:29 UTC, Sakurann commented on openid-4-verifiable-presentations-1_0.md
> +## Mobile Documents or mdocs (ISO/IEC 18013 and ISO/IEC 23220)
```suggestion
## Mobile Documents or mdocs (ISO/IEC 18013 and ISO/IEC 23220 series)
```

2024-03-28 04:30 UTC, Sakurann approved these changes
looks pretty good to me. one of the cleanest explanations of the relationship btw 18013, 23220 series and oid4vp that i have seen

2024-03-28 13:07 UTC, jogu approved these changes

2024-03-28 14:36 UTC, awoie commented
Had to fix some of the references. SessionTranscript is defined in 18013-5/23220-4. OID4VPHandover is defined in 18013-7 and 23220-4. SessionTranscript is always the same for all protocols. OID4VP is just a specific protocol in ISO. Had to adjust the language. For that reason, please review again @Sakurann @jogu .

2024-03-28 15:53 UTC, jogu approved these changes

2024-04-02 19:10 UTC, Sakurann approved these changes
thank you for requesting re-review

2024-04-02 19:13 UTC, tplooker approved these changes

2024-04-02 19:32 UTC, paulbastian approved these changes
Looks good to me. Are we sure we want to exclude all examples?

2024-04-02 19:40 UTC, Sakurann commented
Yeah, I actually had the same question in the back of my mind... 
examples are super useful but they also depend on 18013-7, so keeping them in oid4vp means dependency on 18013-7 (updating them whenever 18013-7 changes), so probably better to remove them from oid4vp

2024-04-02 20:01 UTC, c2bo approved these changes

2024-04-02 21:51 UTC, jogu commented
> Looks good to me. Are we sure we want to exclude all examples?

Aside from the very good reason Kristina mentioned, we also don't actually have any valid examples (there's an error in the ones currently in 18013-7) and they'd be a massive pain to generate.

I think omitting them is the correct thing to do at the current time. Whether we might at some future point want to add them back in is a slightly separate discussion.

2024-04-03 20:50 UTC, merged