fix indentation
openid/OpenID4VP pull request #183
Opened 2024-05-28 18:03 UTC by Sakurann

resolves #133

2024-05-29 08:27 UTC, c2bo requested changes

2024-05-29 08:27 UTC, c2bo commented on examples/response/jarm_jwt_vc_json_post.txt
> +  Content-Type: application/x-www-form-urlencoded
Shouldn't the headers be on the same level?
```suggestion
POST /post HTTP/1.1
Host: client.example.org
Content-Type: application/x-www-form-urlencoded
```

2024-05-31 14:49 UTC, c2bo approved these changes
As commented, I do believe we need another pass at quite a few of the examples to get consistent indentation for everything, but the http request/response examples seem to be fine now.

2024-05-31 14:49 UTC, c2bo commented on openid-4-verifiable-presentations-1_0.md
> +  "redirect_uri":"https://client.example.org/cb#response_code=091535f699ea575c7937fa5f0f454aee"
```suggestion
  "redirect_uri": "https://client.example.org/cb#response_code=091535f699ea575c7937fa5f0f454aee" 
```

2024-05-31 14:49 UTC, c2bo commented on openid-4-verifiable-presentations-1_0.md
> +   "state" : "eyJhb...6-sVA"
```suggestion
   "state": "eyJhb...6-sVA"
```

Looking at this and then at the draft I realized that the JSON examples are also somewhat inconsistent. Some examples seem to be using 3 space indentation (like here), others 2 or 4. Should i create another Issue / PR for this?

2024-06-03 19:48 UTC, Sakurann commented
Which examples..?

2024-06-04 12:14 UTC, c2bo commented
> Which examples..?

https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#section-5.7-8 For example - header and body use different indentation. There were a few examples were e.g., the JSON formatting seemed to be different. I can take a bit of time and collect everything I find into another issue/PR.

2024-06-10 09:32 UTC, Sakurann commented
> I can take a bit of time and collect everything I find into another issue/PR.

@c2bo thank you - that would be great!

2024-06-10 09:34 UTC, merged