Add normative reference to JWK spec
openid/OpenID4VP pull request #242
Opened 2024-09-01 19:26 UTC by selfissued

Fixes #228

2024-09-02 19:23 UTC, David-Chadwick reviewed
Has 7517 also been added to the normative references section?

2024-09-04 07:31 UTC, c2bo commented
> Has 7517 also been added to the normative references section?

That should happen automatically with the syntax (@! should be normative and @ should be informative with mmark)

2024-09-04 07:52 UTC, c2bo approved these changes
When reading the text I started wondering if our references for `client_metadata` need a bit of work though: `jwks` and  `jwks_uri` is used throughout the text but does not reference section 9 where client_metadata is formally introduced with the reference to DCR. I think we should reference section 9 at least once (which is only referenced for `vp_token` right now). I guess that should be a separate issue/PR?

2024-09-04 07:52 UTC, c2bo commented on openid-4-verifiable-presentations-1_0.md
> +* `cnf`: REQUIRED. This claim contains the confirmation method as defined in [@!RFC7800]. It MUST contain a JWK [@!RFC7517] as defined in Section 3.2 of [RFC7800]. This claim determines the public ke
Not sure about this, but felt more natural to me to use the long form when formally mentioning JWK for the first time.
```suggestion
* `cnf`: REQUIRED. This claim contains the confirmation method as defined in [@!RFC7800]. It MUST contain a JSON Web Key [@!RFC7517] as defined in Section 3.2 of [RFC7800]. This claim determines the public key for which's corresponding private key the Verifier MUST proof possession of when presenting the Verifier Attestation JWT. This additional security measure allows the Verifier to obtain a Verifier Attestion JWT from a trusted issuer and use it for a long time independent of that issuer without the risk of an advisary impersonating the Verifier by replaying a captured attestation.
```

2024-09-05 14:37 UTC, Sakurann requested changes
let's fix other typos too if we are doing a PR on this section

2024-09-05 14:38 UTC, Sakurann commented
@c2bo 
> When reading the text I started wondering if our references for client_metadata need a bit of work though: jwks and jwks_uri is used throughout the text but does not reference section 9 where client_metadata is formally introduced with the reference to DCR. I think we should reference section 9 at least once (which is only referenced for vp_token right now). I guess that should be a separate issue/PR?

agree with proposed clarifications. a separate issue/PR would be good.

2024-09-10 15:58 UTC, jogu approved these changes

2024-09-11 13:18 UTC, Sakurann approved these changes

2024-09-11 13:19 UTC, merged