Add transaction_data to allowed parameters in Browser API
openid/OpenID4VP pull request #303
Opened 2024-11-01 04:54 UTC by jogu

This was omitted by accident in the transaction_data PR.

Also updates spec version from 22 to 23.

closes #302

2024-11-01 05:18 UTC, c2bo requested changes

2024-11-01 05:18 UTC, c2bo commented on openid-4-verifiable-presentations-1_0.md
> +* `transaction_data`
We are missing the DCQL as well, right?
```suggestion
* `transaction_data`
* `dcql_query`
```

2024-11-01 15:47 UTC, jogu commented on openid-4-verifiable-presentations-1_0.md
> +* `transaction_data`
Good catch! Applied, thanks!

2024-11-01 15:48 UTC, jogu commented on openid-4-verifiable-presentations-1_0.md
> +   * add `transaction_data` to list of allowed parameters in W3C Digital Credentials API appendix
```suggestion
   * add `transaction_data` & `dcql_query` to list of allowed parameters in W3C Digital Credentials API appendix
```

2024-11-01 20:23 UTC, c2bo approved these changes

2024-11-03 06:42 UTC, bc-pi approved these changes

2024-11-12 15:57 UTC, merged