Remove `client_id_scheme` from Verifier Metadata
openid/OpenID4VP pull request #50
Opened 2023-09-26 13:54 UTC by cobward

There is currently some ambiguity around `client_id_scheme`. This parameter appears in the request object AND the client metadata, which also appears in the request object. There is no text in the specification to define what a wallet should do if it receives a rquest object where these two values do not match.

As I see it there are 3 ways forwards:
1. Remove `client_id_scheme` from Verifier Metadata.
2. Remove `client_id_scheme` from the authz request object, AND make it so that either `client_metadata` or `client_metadata_uri` are always provided in the request object.
3. Add text to describe what a wallet should do if it receives a request object with mismatching `client_id_scheme`.

I have raised this PR with option 1.

2023-09-28 17:17 UTC, Sakurann approved these changes
problem statement and option 1 as a solution makes sense to me.

2023-10-05 15:57 UTC, tlodderstedt approved these changes

2023-10-05 16:00 UTC, awoie approved these changes

2023-10-05 17:05 UTC, bc-pi approved these changes

2023-10-05 17:18 UTC, peppelinux commented
> Remove client_id_scheme from the authz request object, AND make it so that either client_metadata or client_metadata_uri are always provided in the request object.

This is in conflicts with OpenID Federation or any other trust model that requires the metadata be provided by a trusted third party

This PR introduce an important breaking change to some current implementations that uses OpenID Federation for the wallet ecosystem

With this comment I would not say that client_id_scheme must be keep, if removed the text/PR should give guidance about the implementations that requires the metadata with different mechanisms than the authz request object

`client_metadata_uri` is a strategy where its response cannot be just `application/json` but a JWS as well, where required by the trust model

2023-10-05 17:20 UTC, peppelinux requested changes
See https://github.com/openid/OpenID4VP/pull/50#issuecomment-1749341269

2023-10-05 19:38 UTC, Sakurann commented
@peppelinux if wallet is able to obtain verifier's metadata using openid federation, it means that wallet already trusted client_id_scheme `entity_id` in the authorization request. so I do not think you need `client_id_scheme` verifier metadata parameter in the openid federation files.

2023-10-05 19:53 UTC, peppelinux commented
Thank you for clarification @Sakurann , having not  build the preview I was Just worries about the potential impact, but as you said this PR removes the client id scheme just from the metadata

Approved!

PS = Is there any CD to have the preview a of the build for each PR?

2023-10-05 19:53 UTC, peppelinux approved these changes

2023-10-24 16:39 UTC, merged